package com.example.instapets.activities;

import android.app.ProgressDialog;
import android.content.Intent;
import android.graphics.Color;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

import com.example.instapets.R;
import com.example.instapets.utilities.SharedPrefUtils;
import com.google.firebase.firestore.DocumentReference;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.storage.FirebaseStorage;
import com.google.firebase.storage.StorageReference;
import com.example.instapets.fragments.DetailsFragment;
import com.example.instapets.fragments.ProfileImageFragment;
import com.example.instapets.fragments.UsernameFragment;

import java.util.HashMap;

/**
 * this class represent the activity of the info
 * initialization when the user has been just created
 */

public class AddInfoActivity extends AppCompatActivity {
    public enum Fragments {USERNAME, PROFILE_IMAGE, DETAILS}

    public ImageView nextButton;
    public HashMap<String, Object> data;
    public Uri profileImageUri = null;

    public TextView headerText;
    Fragments current;
    DocumentReference userReference;
    private SharedPrefUtils prefUtils;

    //This method is called when the activity is created. Key functionality includes:
    //Setting the status bar color to white, Initializing views and data structures,
    //Setting the initial fragment to the UsernameFragment and adding it to the frame_container.
    //Configuring the nextButton click listener to move to the next fragment.
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            getWindow().setStatusBarColor(Color.parseColor("#FFFFFF"));
        }
        setContentView(R.layout.activity_add_info);
        nextButton = findViewById(R.id.btn_next);
        headerText = findViewById(R.id.txt_header);

        prefUtils = new SharedPrefUtils(this);
        userReference = FirebaseFirestore.getInstance().collection("Users").document(prefUtils.get("email").replace(".", ""));

        //meant to store data related to the user input
        data = new HashMap<>();

        //set the fragment to username fragment
        current = Fragments.USERNAME;
        getSupportFragmentManager().beginTransaction().replace(R.id.frame_container, new UsernameFragment(this)).commit();

        //in case the user clicks next button
        nextButton.setOnClickListener(view -> {
            nextFragment();
        });
    }

    //This method moves between fragments when updating details in our add info activity
    public void nextFragment() {
        if (current == Fragments.USERNAME) {
            getSupportFragmentManager().beginTransaction().replace(R.id.frame_container, new ProfileImageFragment(this)).commit();
            current = Fragments.PROFILE_IMAGE;
        } else if (current == Fragments.PROFILE_IMAGE) {
            getSupportFragmentManager().beginTransaction().replace(R.id.frame_container, new DetailsFragment(this)).commit();
            current = Fragments.DETAILS;
        } else if (current == Fragments.DETAILS) {
            if (profileImageUri != null)
                updateDataWithImage();
            else
                updateData();
        }
    }

    // This method update data to firebase in real time
    //If the update is successful, it navigates the user to the MainActivity.
    // This method is called when the user has completed entering details without an image.
    void updateData() {
        userReference.update(data).addOnCompleteListener(task -> {
            if (task.isSuccessful()) {
                Intent intent = new Intent(this, MainActivity.class);
                intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK | Intent.FLAG_ACTIVITY_CLEAR_TOP);
                startActivity(intent);
                finish();
            }
        });
    }

    //This method is for storing the chosen image to the FireBase
    // After a successful upload, calls updateData() to complete the data update.
    // This method is called when the user has chosen a profile image.
    void updateDataWithImage() {
        //bringing the the FireBase instance for updates
        StorageReference storageReference = FirebaseStorage.getInstance().getReference();
        ProgressDialog progressDialog = new ProgressDialog(this);

        //informs that the user's profile update is in progress.
        progressDialog.setTitle("Saving Profile...");
        progressDialog.show();

         // constructs a path for the profile picture in Firebase Storage based
         // on the user's email address. The postId variable is generated by replacing
         // dots in the user's email address with empty strings.
        String postId = prefUtils.get("email").replace(".", "");
        StorageReference ref = storageReference.child("Profile Pictures/" + postId);

        //Uploading Profile Image to Firebase Storage
        ref.putFile(profileImageUri).addOnCompleteListener(task0 -> {
            if (task0.isSuccessful()) {
                storageReference.child("Profile Pictures/").child(postId).getDownloadUrl().addOnCompleteListener(task -> {
                    if (task.isSuccessful()) {
                        data.put("profileImageUrl", task.getResult().toString());
                        updateData();
                    }
                    progressDialog.dismiss();
                });
            } else {
                Toast.makeText(this, "Failed " + task0.getException().getMessage(), Toast.LENGTH_SHORT).show();
                progressDialog.dismiss();
            }

             // success or failure, the ProgressDialog is dismissed to indicate that
             // the process has completed.

        }).addOnProgressListener(taskSnapshot -> {
            double progress = ((100.0 * taskSnapshot.getBytesTransferred() / taskSnapshot.getTotalByteCount()));
            progressDialog.setMessage("Saving " + (int) progress + "%");
        });
    }
}